import 'package:flutter/material.dart';

enum AppLanguage {
  english,
  arabic,
  malay,
  indonesian,
  urdu,
  hindi,
  turkish,
  bengali,
  persian,
  french,
  german,
  spanish,
  russian,
  italian,
  portuguese,
  dutch,
  chinese,
  japanese,
  korean,
  azerbaijani,
  bosnian,
  czech,
  polish,
  romanian,
  swedish,
  albanian,
  uzbek,
  tatar,
  uyghur,
  amharic,
  bashkir,
  berber,
  bulgarian,
  chechen,
  divehi,
  hausa,
  kurdish,
  malayalam,
  burmese,
  norwegian,
  pashto,
  sindhi,
  sinhala,
  somali,
  swahili,
  tamil,
  tajik,
  thai,
}

extension AppLanguageX on AppLanguage {
  String get code => switch (this) {
    AppLanguage.english => 'en',
    AppLanguage.arabic => 'ar',
    AppLanguage.malay => 'ms',
    AppLanguage.indonesian => 'id',
    AppLanguage.urdu => 'ur',
    AppLanguage.hindi => 'hi',
    AppLanguage.turkish => 'tr',
    AppLanguage.bengali => 'bn',
    AppLanguage.persian => 'fa',
    AppLanguage.french => 'fr',
    AppLanguage.german => 'de',
    AppLanguage.spanish => 'es',
    AppLanguage.russian => 'ru',
    AppLanguage.italian => 'it',
    AppLanguage.portuguese => 'pt',
    AppLanguage.dutch => 'nl',
    AppLanguage.chinese => 'zh',
    AppLanguage.japanese => 'ja',
    AppLanguage.korean => 'ko',
    AppLanguage.azerbaijani => 'az',
    AppLanguage.bosnian => 'bs',
    AppLanguage.czech => 'cs',
    AppLanguage.polish => 'pl',
    AppLanguage.romanian => 'ro',
    AppLanguage.swedish => 'sv',
    AppLanguage.albanian => 'sq',
    AppLanguage.uzbek => 'uz',
    AppLanguage.tatar => 'tt',
    AppLanguage.uyghur => 'ug',
    AppLanguage.amharic => 'am',
    AppLanguage.bashkir => 'ba',
    AppLanguage.berber => 'ber',
    AppLanguage.bulgarian => 'bg',
    AppLanguage.chechen => 'ce',
    AppLanguage.divehi => 'dv',
    AppLanguage.hausa => 'ha',
    AppLanguage.kurdish => 'ku',
    AppLanguage.malayalam => 'ml',
    AppLanguage.burmese => 'my',
    AppLanguage.norwegian => 'no',
    AppLanguage.pashto => 'ps',
    AppLanguage.sindhi => 'sd',
    AppLanguage.sinhala => 'si',
    AppLanguage.somali => 'so',
    AppLanguage.swahili => 'sw',
    AppLanguage.tamil => 'ta',
    AppLanguage.tajik => 'tg',
    AppLanguage.thai => 'th',
  };

  Locale get locale => Locale(code);

  String get englishName => switch (this) {
    AppLanguage.english => 'English',
    AppLanguage.arabic => 'Arabic',
    AppLanguage.malay => 'Malay',
    AppLanguage.indonesian => 'Indonesian',
    AppLanguage.urdu => 'Urdu',
    AppLanguage.hindi => 'Hindi',
    AppLanguage.turkish => 'Turkish',
    AppLanguage.bengali => 'Bengali',
    AppLanguage.persian => 'Persian',
    AppLanguage.french => 'French',
    AppLanguage.german => 'German',
    AppLanguage.spanish => 'Spanish',
    AppLanguage.russian => 'Russian',
    AppLanguage.italian => 'Italian',
    AppLanguage.portuguese => 'Portuguese',
    AppLanguage.dutch => 'Dutch',
    AppLanguage.chinese => 'Chinese',
    AppLanguage.japanese => 'Japanese',
    AppLanguage.korean => 'Korean',
    AppLanguage.azerbaijani => 'Azerbaijani',
    AppLanguage.bosnian => 'Bosnian',
    AppLanguage.czech => 'Czech',
    AppLanguage.polish => 'Polish',
    AppLanguage.romanian => 'Romanian',
    AppLanguage.swedish => 'Swedish',
    AppLanguage.albanian => 'Albanian',
    AppLanguage.uzbek => 'Uzbek',
    AppLanguage.tatar => 'Tatar',
    AppLanguage.uyghur => 'Uyghur',
    AppLanguage.amharic => 'Amharic',
    AppLanguage.bashkir => 'Bashkir',
    AppLanguage.berber => 'Berber',
    AppLanguage.bulgarian => 'Bulgarian',
    AppLanguage.chechen => 'Chechen',
    AppLanguage.divehi => 'Divehi',
    AppLanguage.hausa => 'Hausa',
    AppLanguage.kurdish => 'Kurdish',
    AppLanguage.malayalam => 'Malayalam',
    AppLanguage.burmese => 'Burmese',
    AppLanguage.norwegian => 'Norwegian',
    AppLanguage.pashto => 'Pashto',
    AppLanguage.sindhi => 'Sindhi',
    AppLanguage.sinhala => 'Sinhala',
    AppLanguage.somali => 'Somali',
    AppLanguage.swahili => 'Swahili',
    AppLanguage.tamil => 'Tamil',
    AppLanguage.tajik => 'Tajik',
    AppLanguage.thai => 'Thai',
  };

  String get nativeName => switch (this) {
    AppLanguage.english => 'English',
    AppLanguage.arabic => '\u0627\u0644\u0639\u0631\u0628\u064a\u0629',
    AppLanguage.malay => 'Bahasa Melayu',
    AppLanguage.indonesian => 'Bahasa Indonesia',
    AppLanguage.urdu => '\u0627\u0631\u062f\u0648',
    AppLanguage.hindi => '\u0939\u093f\u0928\u094d\u0926\u0940',
    AppLanguage.turkish => 'T\u00fcrk\u00e7e',
    AppLanguage.bengali => '\u09ac\u09be\u0982\u09b2\u09be',
    AppLanguage.persian => '\u0641\u0627\u0631\u0633\u06cc',
    AppLanguage.french => 'Fran\u00e7ais',
    AppLanguage.german => 'Deutsch',
    AppLanguage.spanish => 'Espa\u00f1ol',
    AppLanguage.russian => '\u0420\u0443\u0441\u0441\u043a\u0438\u0439',
    AppLanguage.italian => 'Italiano',
    AppLanguage.portuguese => 'Portugu\u00eas',
    AppLanguage.dutch => 'Nederlands',
    AppLanguage.chinese => '\u4e2d\u6587',
    AppLanguage.japanese => '\u65e5\u672c\u8a9e',
    AppLanguage.korean => '\ud55c\uad6d\uc5b4',
    AppLanguage.azerbaijani => 'Az\u0259rbaycan dili',
    AppLanguage.bosnian => 'Bosanski',
    AppLanguage.czech => '\u010ce\u0161tina',
    AppLanguage.polish => 'Polski',
    AppLanguage.romanian => 'Rom\u00e2n\u0103',
    AppLanguage.swedish => 'Svenska',
    AppLanguage.albanian => 'Shqip',
    AppLanguage.uzbek => 'O\'zbek',
    AppLanguage.tatar => '\u0422\u0430\u0442\u0430\u0440\u0447\u0430',
    AppLanguage.uyghur => '\u0626\u06c7\u064a\u063a\u06c7\u0631\u0686\u06d5',
    AppLanguage.amharic => '\u12a0\u121b\u122d\u129b',
    AppLanguage.bashkir =>
      '\u0411\u0430\u0448\u04a1\u043e\u0440\u0442\u0441\u0430',
    AppLanguage.berber => 'Tamazi\u0263t',
    AppLanguage.bulgarian =>
      '\u0411\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438',
    AppLanguage.chechen => '\u041d\u043e\u0445\u0447\u0438\u0439\u043d',
    AppLanguage.divehi => '\u078b\u07a8\u0788\u07ac\u0780\u07a8',
    AppLanguage.hausa => 'Hausa',
    AppLanguage.kurdish => 'Kurd\u00ee',
    AppLanguage.malayalam => '\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02',
    AppLanguage.burmese => '\u1019\u103c\u1014\u103a\u1019\u102c',
    AppLanguage.norwegian => 'Norsk',
    AppLanguage.pashto => '\u067e\u069a\u062a\u0648',
    AppLanguage.sindhi => '\u0633\u0646\u068c\u064a',
    AppLanguage.sinhala => '\u0dc3\u0dd2\u0d82\u0dc4\u0dbd',
    AppLanguage.somali => 'Soomaaliga',
    AppLanguage.swahili => 'Kiswahili',
    AppLanguage.tamil => '\u0ba4\u0bae\u0bbf\u0bb4\u0bcd',
    AppLanguage.tajik => '\u0422\u043e\u04b7\u0438\u043a\u04e3',
    AppLanguage.thai => '\u0e44\u0e17\u0e22',
  };

  String get translationAssetPath =>
      'assets/data/quran_translations/$code.json';

  static AppLanguage fromCode(String? value) {
    return AppLanguage.values.firstWhere(
      (language) => language.code == value,
      orElse: () => AppLanguage.english,
    );
  }
}
